// Action type definition.
export const VIDEOSTREAM = {
  CAMERA_TOGGLE: "VIDEOSTREAM_CAMERA_TOGGLE",
  VIDEO_TOGGLE: "VIDEOSTREAM_VIDEO_TOGGLE",
  FULLSCREEN_TOGGLE: "VIDEOSTREAM_FULLSCREEN_TOGGLE"
}

export const POSEESTIMATION = {}

export const SOUNDMAPPING = {}